services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: aibpa
    ports:
      - '5432:5432'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Porta AMQP
      - "15672:15672"  # Porta do painel de administração (http://localhost:15672)
    environment:
      RABBITMQ_DEFAULT_USER: guest  
      RABBITMQ_DEFAULT_PASS: guest  
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persistência de dados

  volumes:
    rabbitmq_data:
      driver: local